events{
    worker_connection 1024;
}

http{
    limit_req_zone $binary_remote_address zone=api:10m rate=10r/s;

    upstream node_app{
    server host.docker.internal:3339;
    }

    sever{
        listen 80;
        server_name localhost;

        location/api/task/{
            limit_request zone=task burst=10 nodelay;
            proxy_pass http://node_app;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host; 
        }
    }
}